version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: finquarium
      POSTGRES_PASSWORD: finquarium
      POSTGRES_DB: finquarium
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: